loan_application/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('details.urls')),
    path('loans/', include('loans.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

loans/urls.py
from details.views import BorrowerDetailView, LoansView
from loans.views import FinalView, HomeLoanView, CarLoanView
from django.urls import path
from . import views

urlpatterns = [
    path('home/',HomeLoanView.as_view(),name='home-loan'),
    # path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('car/',CarLoanView.as_view(),name='car-loan'),
    # path('ajax/load-models/', views.load_models, name='ajax_load_models'),
    path('credit-score/', views.get_credit, name='credit-score'),
    path('options/', LoansView.as_view(), name='options'),
    path('verification/', views.get_pan, name='verify'),
    path('final/', FinalView.as_view(), name='final'),
    ]

loans/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.


class State(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class City(models.Model):
    state = models.ForeignKey(State, on_delete=CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Car_Brands(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Car_Models(models.Model):
    brand = models.ForeignKey(Car_Brands, on_delete=CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class HomeLoan(models.Model):
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    purchase_price = models.BigIntegerField(null=True)
    down_payment = models.IntegerField(null=True)
    desired_loan = models.BigIntegerField(null=True)

class CarLoan(models.Model):
    car_brands = models.ForeignKey(Car_Brands, on_delete=models.SET_NULL, null=True)
    car_models = models.ForeignKey(Car_Models, on_delete=models.SET_NULL, null=True)
    purchase_price = models.BigIntegerField()
    down_payment = models.IntegerField()
    desired_loan = models.BigIntegerField()

loans/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from .models import City, HomeLoan, CarLoan, Car_Models
from details.models import Verification

class HomeLoanForm(forms.ModelForm):
    class Meta:
        model = HomeLoan
        fields = ['state','city','purchase_price','down_payment','desired_loan']

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['city'].queryset = City.objects.none()

class CarLoanForm(forms.ModelForm):
    class Meta:
        model = CarLoan
        fields = ['car_brands','car_models','purchase_price','down_payment','desired_loan']

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['car_models'].queryset = Car_Models.objects.none()


class CreditScoreForm(forms.Form):
    age = forms.IntegerField()
    annual_income = forms.IntegerField()


class Verification(forms.ModelForm):
    class Meta:
        model = Verification
        fields = ['aadhar_number','pan_number']

loans/views.py
from django.http import response
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from .models import Car_Models, HomeLoan, CarLoan, City, State
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView
from .forms import CarLoanForm, CreditScoreForm, HomeLoanForm
from rest_framework.decorators import api_view
import requests
# Create your views here.

class HomeLoanView(CreateView):
    template_name = "loans/home_loan.html"
    model = HomeLoan
    form_class = HomeLoanForm
    success_url = "/loans/credit-score"


# def load_cities(request):
#     state_id = request.GET.get('state')
#     cities = City.objects.filter(state_id=state_id).order_by('name')
#     return render(request, 'loans/city_dropdown_list_options.html', {'cities': cities})


class CarLoanView(CreateView):
    template_name = "loans/car_loan.html"
    model = CarLoan
    form_class = CarLoanForm
    success_url = "/loans/credit-score"


# def load_models(request):
#     brand_id = request.GET.get('car_brands')
#     models = Car_Models.objects.filter(brand_id=brand_id).order_by('name')
#     return render(request, 'loans/model_dropdown_list_options.html', {'models': models})


def get_credit(request):
    # if request.method == 'POST':
    #     form = CreditScoreForm(request.POST)
    #     if form.is_valid():
    #         age = form.cleaned_data['age']
    #         a_i = form.cleaned_data['annual_income']

            URL = "https://31j0q0noye.execute-api.us-east-1.amazonaws.com/hackathon/creditscore?age=22&annualIncome=948543"
            # PARMAS = { 'age':age,
            #             'annualIncome': a_i }
            response=requests.get(url = URL).json()
            eligibility_status = response['eligiblityStatus']
            if eligibility_status == 1:
                return render(request, 'loans/positive.html',{'response':response})
            return render(request, 'loans/negative.html',{'response':response})


def get_pan(request):

    URL = "https://31j0q0noye.execute-api.us-east-1.amazonaws.com/hackathon/panverify?pancard=CIHPR9246B"
    response=requests.get(url = URL).json()
    pan = response['validPan']
    if pan == 'True':
        return render(request, 'loans/verification.html',{'response':response})

class FinalView(TemplateView):
    template_name = 'loans/final.html'

loans/templates/loans/car_loan.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

<title>Loan Form</title>

  {% block style %}
    <link rel="stylesheet" href={% static 'loans/form.css' %}>
  {% endblock style %}


</head>
{% block content %}
<body>
    
    <div id="task-container">
        <div id="form-wrapper">
        <form method="post" id="loanForm" action="/loans/car/">
          {% csrf_token %}
    
            {{form|crispy}}
        
          <button class="btn btn-success" type="submit">Continue</button>
      </form>
          </div>
        </div>
      
    {% comment %} <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
     data-models-url="{% url 'ajax_load_models' %}"
  <script>
    $("#id_car_brands").change(function () {
      var url = $("#loanForm").attr("data-models-url");  // get the url of the `load_cities` view
      var brandId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'car_brands': brandId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_car_models").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script> {% endcomment %}

</body>
{% endblock content %}
</html>

loans/templates/loans/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

loans/templates/loans/credit_score.html
{% extends 'base.html' %}

{% block content %}
    {% csrf_token %}
    <form id="get-form" method="get">
    {{ response }}
    <input id="submit" class="btn" type="submit" />
    </form>

  
{% endblock %}

loans/templates/loans/final.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

<title>Loan Form</title>

    {% block style %}
        <link rel="stylesheet" href={% static 'details/form.css' %}>
    {% endblock style %}



</head>
{% block content %}
<body>
    
    <div id="task-container">
        <div id="form-wrapper">
        <center>
    <img src={% static 'details/third.jpg' %} class="rounded" alt="home loan" height="500px" width="500px">
        <div class="para">
            <h3>Thanks for applying</h3> 
            <h3 class="ref">Your Reference number:</h3>
            <span style="color: limegreen;"><h4>2</h4>.</span>
        </div>
            </center>
          </div>
        </div>

</body>
{% endblock content %}
</html>

loans/templates/loans/home_loan.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

<title>Loan Form</title>

 {% block style %}
    <link rel="stylesheet" href={% static 'loans/form.css' %}>
  {% endblock style %}


{% block content %}

  <div id="task-container">
        <div id="form-wrapper">
        <form method="post" id="loanForm" action="/loans/home/">
          {% csrf_token %}
          <div id="flex-wrapper">
            {{form|crispy}}
          </div>
          <button class="btn btn-success" type="submit">Save</button>
      </form>
          </div>
        </div>

  {% comment %} <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  data-cities-url="{% url 'ajax_load_cities' %}"
  <script>
    $("#id_state").change(function () {
      var url = $("#loanForm").attr("data-cities-url");  // get the url of the `load_cities` view
      var stateId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'state': stateId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script> {% endcomment %}

{% endblock %}

loans/templates/loans/loans.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

<title>Loan Form</title>

    {% block style %}
        <link rel="stylesheet" href={% static 'details/form.css' %}>
    {% endblock style %}



</head>
{% block content %}
<body>
    
    <div id="task-container">
        <div id="form-wrapper">
            <div class="total">
        <div class="home">
            <a href={% url 'home-loan' %}>
                <center>
        <img src={% static 'loans/home.jpg' %} class="rounded" alt="home loan" height="300px" width="300px"></center></a>
        </div>
        <div class="car">
            <a href={% url 'car-loan' %}>
                <center>
        <img src={% static 'loans/car.png' %} class="rounded" alt="home loan" height="300px" width="300px"></center></a>
        </div>
      </div> 
          </div>
        </div>
      

</body>
{% endblock content %}
</html>

loans/templates/loans/model_dropdown_list_options.html
<option value="">---------</option>
{% for model in models %}
<option value="{{ model.pk }}">{{ model.name }}</option>
{% endfor %}

loans/templates/loans/negative.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

<title>Loan Form</title>

    {% block style %}
        <link rel="stylesheet" href={% static 'details/form.css' %}>
    {% endblock style %}



</head>
{% block content %}
<body>
    
    <div id="task-container">
        <div id="form-wrapper">
        <img src={% static 'loans/credit.jpeg' %} class="rounded" alt="credit" height="500px" width="500px">
        <h4 style="text-align: center;">Your Credit Score</h4>
    <p style="text-align: center">Your credit score is below our desired value.
    <br>Sorry you cannot apply for this loan.</p><br></center>
            <center><h1>{{ response.creditScore }}</h1></center></br>
            <center><button class="btn btn-success">Continue</button></center>
          </div>
        </div>
      
 

</body>
{% endblock content %}
</html>

loans/templates/loans/positive.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

<title>Loan Form</title>

    {% block style %}
        <link rel="stylesheet" href={% static 'details/form.css' %}>
    {% endblock style %}



</head>
{% block content %}
<body>
    
    <div id="task-container">
        <div id="form-wrapper">
        <img src={% static 'loans/credit.jpeg' %} class="rounded" alt="credit" height="500px" width="500px">
        <h4 style="text-align: center;">Your Credit Score</h4>
    <p style="text-align: center">You have a good credit score you can proceed
    <br>with the application.</p><br></center>
            <center><h1>{{ response.creditScore }}</h1></center></br>
            <center><button class="btn btn-success"><a href={% url 'verify' %}>Continue</a></button></center>
          </div>
        </div>
      


</body>
{% endblock content %}
</html>

loans/templates/loans/verification.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

<title>Loan Form</title>

    {% block style %}
        <link rel="stylesheet" href={% static 'details/form.css' %}>
    {% endblock style %}



</head>
{% block content %}
<body>
    
    <div id="task-container">
        <div id="form-wrapper">
        <img src={% static 'details/third.jpg' %} class="rounded" alt="home loan" height="500px" width="500px">
        <h4 style="text-align: center;">You're Ready to Submit</h4>
    <p style="text-align: center">By selecting Submit Button you will no longer be
    <br>able to access your application. Your loan officer will
    <br> follow up with you as soon as possible</p><br></center>
            <input type="checkbox" unchecked/>  Borrower: I consent business electronically and agree to <span style="color: limegreen;">the consent forms.</span>
            <center><button class="btn btn-success"><a href={% url 'final' %}>Continue</a></button></center>
          </div>
        </div>

</body>
{% endblock content %}
</html>